Add Top 200 Polygon Tokens
tallycash/token-list pull request #39
Opened 2022-06-14 18:54 UTC by 0xDaedalus

This list was derived by filtering the [official polygon tokenlist](https://github.com/maticnetwork/polygon-token-list/blob/master/src/tokens/allTokens.json) via [this query](https://dune.com/queries/909790?d=7)

For posterity - query pasted below:
```
SELECT SUM(usd_amount) as volume, token_b_address
from dex.trades
where block_time > '2021-05-01'
and block_time < '2021-06-14'
and project = 'Quickswap'
and usd_amount > 1
group by token_b_address
order by volume desc
LIMIT 200;
```

2022-06-17 11:07 UTC, greg-nagy requested changes
This is a really good start, and I love that we are utilising dune for this ❤️

In the icon list I think we should do some clean up, before we merge this. Missing icons: btu, emon, ghst, iq (html instead of png), move.

Can't verify the compiled list of tokens, but I am comfortable trusting you with it, or defer the decesion to someone else. 

Non blocking questions: 
- Why 2021-05-01 - 2021-06-14?
- Does this also include cex trades? Or dex trades are representative enough?

2022-06-17 13:05 UTC, 0xDaedalus commented on file
> +Invalid token in file, can't find logo image - chains/137.json - [object Object][2K[1G[31merror[39m Command failed with exit code 65.
Trash - good catch

2022-06-17 13:11 UTC, 0xDaedalus commented
> Why 2021-05-01 - 2021-06-14?

The more deterministic the list - the better - so someone can verify the list.

>  but I am comfortable trusting you with it

Someone should probably do a spot-check of at least a few - even if I'm a trusted party we should not necessarily trust the 3rd party source.  Its definitely possible that there are malicious tokens caught in that query (although highly unlikely).

> In the icon list I think we should do some clean up, before we merge this. Missing icons: btu, emon, ghst, iq (html instead of png), move.

Once again good catch - a great example of someone (me) blindly trusting 3rd party sources without verifying.

2022-06-21 07:30 UTC, greg-nagy requested changes
The not svg icons seem to be corrupted.

btu, emon, ghst, iq, move

github is not able to render them, and couldn't open them after download

We either should find icons manually, or remove them. My preference is on the former.

2022-06-21 11:39 UTC, Shadowfiend commented
Approach feels sound on my end, though agree we should clean up any bad logos. If we need help sourcing the right ones perhaps we can reach out to the community?

2022-06-21 14:45 UTC, 0xDaedalus commented
> Removing the icons from the list could work but I think it would be better to find the proper icons.

Why don't we add this as a community bounty - we have plenty of tokens in the app already that lack logos

2022-06-24 13:16 UTC, greg-nagy commented
>> think it would be better to find the proper icons.

> Why don't we add this as a community bounty - we have plenty of tokens in the app already that lack logos

I think this is a pretty good idea. 

The thing I feel strongly about is not committing broken images if we know they are broken. 
I don't feel that strongly about finding the proper icons now, or just removing them and maybe creating a community bounty.

2022-06-24 13:41 UTC, 0xDaedalus commented
Whoops! - sorry about that! 🙇 I thought I'd gotten all of them.

2022-06-24 16:29 UTC, greg-nagy commented
@0xDaedalus do you want somebody to spot-check the token list or you feel good about merging?

2022-06-27 14:20 UTC, 0xDaedalus commented
From a security POV yes we should probably not add tokens without spot-checking at least some of the set.

2022-06-29 16:40 UTC, mhluongo requested changes
My eyes are bleeding! but I spot-checked the list heavily.

I think we should be consistent about the "PoS" naming scheme, or move it to a schema extension that we label for future bridging metadata goodness. After that we should be gtg

2022-06-29 16:40 UTC, mhluongo commented on chains/137.json
> +    "symbol": "ETH",
Is there a reason we want to call this "ETH" and not "WETH"?

2022-06-29 16:40 UTC, mhluongo commented on chains/137.json
> +    "address": "0xd6df932a45c0f255f85145f286ea0b292b21c90b",
PoS

2022-06-29 16:40 UTC, mhluongo commented on chains/137.json
> +    "address": "0x1bfd67037b42cf73acf2047067bd4f2c47d9bfd6",
PoS

2022-06-29 16:40 UTC, mhluongo commented on chains/137.json
> +    "address": "0x1bfd67037b42cf73acf2047067bd4f2c47d9bfd6",
Thinking about it, we could use a list extension here to label these as PoS if we want

2022-06-29 16:40 UTC, mhluongo commented on chains/137.json
> +    "address": "0x385eeac5cb85a38a9a07a70c73e0a3271cfb54a7"
PoS

2022-06-29 16:40 UTC, mhluongo commented on chains/137.json
> +    "address": "0x7c28F627eA3aEc8B882b51eb1935f66e5b875714"
FDV is $19k, we should remove

2022-06-29 16:40 UTC, mhluongo commented on chains/137.json
> +    "address": "0x8Ba941b64901E306667a287A370F145d98811096",
Only 50 holders, I suggest we snip it

2022-06-29 16:40 UTC, mhluongo commented on chains/137.json
> +    "address": "0x104592a158490a9228070E0A8e5343B499e125D0",
PoS

2022-06-29 16:40 UTC, mhluongo commented on chains/137.json
> +    "address": "0x3e121107F6F22DA4911079845a470757aF4e1A1b",
PoS

2022-07-01 13:07 UTC, 0xDaedalus commented on chains/137.json
> +    "name": "Tether USD",
labled 👍

2022-07-01 15:02 UTC, mhluongo commented on chains/137.json
> +    "symbol": "ETH",
Funny, the contract still say WETH but :shrug:

2022-07-01 15:06 UTC, mhluongo approved these changes
LFG :rocket:

2022-07-01 15:06 UTC, merged